services:
  - type: web
    name: voicegen-bd
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: WEBHOOK_SECRET
        sync: false

      - key: WEBHOOK_URL
        sync: false

      - key: PORT
        value: "10000"
